# Generated by Django 2.0.7 on 2018-10-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('session', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
            ],
        ),
    ]
